### PR TITLE
chore : setup project for Innovision 2024

### PR DESCRIPTION
**Pull request by Srish-ty**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Comment by Srish-ty** [comment]
@Shurtu-gal , please review

**Review by Shurtu-gal — CHANGES_REQUESTED** [review]
@Srish-ty could you add the prettier:check and other scripts in package.json.

**Comment by Srish-ty** [comment]
> @Srish-ty could you add the prettier:check and other scripts in package.json.

Done. https://github.com/dscnitrourkela/project-raisin/pull/117/commits/4f4aa61b393de674d1bd2eab8d48fb7e1b60d55f

**Review by Shurtu-gal — CHANGES_REQUESTED** [review]
@Srish-ty Both build and ci-cd are failing.

**Review by Shurtu-gal — APPROVED** [review]
LGTM

**Pull request merged**
